name: Build RedisGraph

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake m4 automake peg libtool autoconf python3

    - name: Build the project
      run: |
        make

    - name: Upload RedisGraph binary
      uses: actions/upload-artifact@v3
      with:
        name: redisgraph
        path: src/redisgraph.so
